// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0UD64-9SXrfL3vrrjOKqNHJmoiUGhaGE',
    appId: '1:208852052256:web:d78b4a6376f3ab5e214f45',
    messagingSenderId: '208852052256',
    projectId: 'findvet-4ec13',
    authDomain: 'findvet-4ec13.firebaseapp.com',
    storageBucket: 'findvet-4ec13.appspot.com',
    measurementId: 'G-R4KK1KF40W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2C-aQ9l-pm7nNAWDv6lYEWPJo-sjlUcA',
    appId: '1:208852052256:android:6f70c450cda24686214f45',
    messagingSenderId: '208852052256',
    projectId: 'findvet-4ec13',
    storageBucket: 'findvet-4ec13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKMZYzs-_VQPaiorfXU3uzd7DcumAJViI',
    appId: '1:208852052256:ios:306f32f34fa6c2c4214f45',
    messagingSenderId: '208852052256',
    projectId: 'findvet-4ec13',
    storageBucket: 'findvet-4ec13.appspot.com',
    iosClientId: '208852052256-kpqstn5m3rrl0ptcgmm9gssm81t4i5f2.apps.googleusercontent.com',
    iosBundleId: 'cls',
  );
}
